# Generated by Django 4.0.3 on 2022-04-07 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='category',
            field=models.ManyToManyField(blank=True, default='all', to='tapp.category'),
        ),
    ]
