# Generated by Django 4.0.3 on 2022-04-07 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapp', '0002_alter_category_category_slug_alter_thread_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
