# Generated by Django 4.0.3 on 2022-04-07 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapp', '0003_alter_category_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
