# Generated by Django 4.0.3 on 2022-04-07 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('category_slug', models.SlugField(max_length=200, unique=True)),
                ('category_description', models.TextField(max_length=300)),
                ('category_icon_code', models.CharField(default='fa fa-code', help_text='ex: fa fa-code , look fontawesome 4.7 icons', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Twitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_name', models.CharField(max_length=200)),
                ('twitter_link', models.URLField()),
                ('twitter_image', models.ImageField(blank=True, upload_to='twitter_image')),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_title', models.CharField(max_length=200)),
                ('thread_link', models.URLField()),
                ('thread_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ManyToManyField(blank=True, to='tapp.category')),
                ('twitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tapp.twitter')),
            ],
        ),
    ]
